baseURL: https://lieskjur.github.io/Notes
languageCode: en-us
title: Pozn√°mky

theme: hugo-book
# enableGitInfo: true

params:
  # BookTheme : "auto" # light(default)/dark/auto
  BookRepo: https://github.com/lieskjur/Notes
  BookEditPath: edit/main/
  BookDateFormat: "January 2, 2006"